In [1]:
import datetime
print(datetime.datetime.now())

2025-08-09 18:44:00.142101


In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.14.0


In [3]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector=tf.constant([10,10])

In [6]:
vector.ndim

1

In [7]:
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [10]:
another_matrix=tf.constant([[10.,7.],[3.,2.],[8.,9.]],dtype=tf.float16)

In [11]:
another_matrix.ndim

2

In [13]:
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

In [16]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])


In [17]:
# will error(requires the .assign method)
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [18]:
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([9, 7])>

In [19]:
# Will error (can't change tf.constant())
unchangeable_tensor[0].assign(8)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [22]:
# Create two random tensors
random_1=tf.random.Generator.from_seed(42) # set the seed for reproductivity
random_1=random_1.normal(shape=(3,2)) # create tensor from a normal distribution
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [23]:
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [24]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [ ]:
# Shuffle in the same order every time 
# Set the global random seed
tf.random.set_seed(42)
# Set the operation random seed
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [26]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [27]:
tf.ones(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [28]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [38]:
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
A=tf.constant(numpy_A,
              shape=[2,4,3])
numpy_A,A # shape total (2*4*3) has to match the number of elements in the array

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

In [39]:
rank_4_tensor=tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [41]:
rank_4_tensor.dtype, rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(tf.float32,
 TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [42]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [43]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
rank_2_tensor=tf.constant([[10,7],[3,4]])
# Get the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [47]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis] # ... means all dimension prior to
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [49]:
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [50]:
A+10

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31],
        [32, 33, 34]]])>

In [51]:
A*10

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180],
        [190, 200, 210],
        [220, 230, 240]]])>

In [52]:
A-10

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[-9, -8, -7],
        [-6, -5, -4],
        [-3, -2, -1],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])>

In [53]:
tf.multiply(A,10)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]],

       [[130, 140, 150],
        [160, 170, 180],
        [190, 200, 210],
        [220, 230, 240]]])>

In [54]:
print(A)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]], shape=(2, 4, 3), dtype=int32)


In [57]:
random_1=tf.random.Generator.from_seed(42)

In [65]:
B=random_1.normal(shape=(2,3))@random_1.normal(shape=(3,3))

In [64]:
tf.matmul(random_1.normal(shape=(1,2)),random_1.normal(shape=(2,2)))

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.30651996, 0.5464553 ]], dtype=float32)>

In [67]:
B.shape
tf.reshape(B,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.27314577,  0.07813188],
       [-0.41684484,  2.0042782 ],
       [ 1.9707894 ,  0.1208508 ]], dtype=float32)>

In [68]:
B@tf.reshape(B,shape=(3,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.77947366,  0.12756339],
       [-0.03588185,  4.1212134 ]], dtype=float32)>

In [69]:
tf.transpose(B)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.27314577,  2.0042782 ],
       [ 0.07813188,  1.9707894 ],
       [-0.41684484,  0.1208508 ]], dtype=float32)>

In [70]:
tf.matmul(tf.transpose(B),B)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4.0917397 , 3.9713516 , 0.12835923],
       [3.9713516 , 3.8901157 , 0.20560262],
       [0.12835923, 0.20560262, 0.18836454]], dtype=float32)>

In [72]:
tf.matmul(a=B,b=B,transpose_a=True,transpose_b=False)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4.0917397 , 3.9713516 , 0.12835923],
       [3.9713516 , 3.8901157 , 0.20560262],
       [0.12835923, 0.20560262, 0.18836454]], dtype=float32)>

In [75]:
# Dot product on X and Y
tf.tensordot(tf.transpose(B),B,axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4.0917397 , 3.9713516 , 0.12835923],
       [3.9713516 , 3.8901157 , 0.20560262],
       [0.12835923, 0.20560262, 0.18836454]], dtype=float32)>

In [78]:
B.shape, tf.reshape(B,(3,2))==tf.transpose(B)

(TensorShape([2, 3]),
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True, False],
        [False, False],
        [False,  True]])>)

As you can see, the outputs of `tf.reshape()` and `tf.transpose()` when called on Y, even though they have the same shape, are different.

`tf.reshape()` change the shape of the given tensor(first) and then insert values in order they appear.

In [80]:
B=tf.constant([1.2,2.1])
C=tf.constant([1,2])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 2.1], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>)

In [82]:
B=tf.cast(B,dtype=tf.float16)

In [84]:
C=tf.cast(C,dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [85]:
D=tf.constant([[-2,4],[-4,3]])
tf.abs(D)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [4, 3]])>

`tf.reduce_max()` 
`tf.reduce_min()`
`tf.reduce_mean()`
`tf.reduce_sum()`

In [86]:
EE=tf.constant(np.random.randint(low=0,high=100,size=50))
EE

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([78, 73, 16, 27, 12, 36, 66, 85, 11, 85, 36, 27, 14, 70, 85, 79, 15,
        6, 81, 65, 84, 62, 96, 32, 17, 68, 67, 10,  2, 46, 27, 59,  9, 31,
        9, 27, 99,  4, 58, 91, 97, 74, 70, 48, 63, 87, 22, 41, 84, 90])>

In [87]:
tf.reduce_sum(EE)

<tf.Tensor: shape=(), dtype=int32, numpy=2541>

In [88]:
tf.reduce_min(EE)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [89]:
tf.reduce_max(EE)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [90]:
tf.reduce_mean(EE)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

`tf.argmax()`-Find the position of the maximum element in a given tensor.
`tf.argmin()`-Find the position of the minimum element in a given tensor.

In [93]:
F=tf.constant(np.random.random(40))
F

<tf.Tensor: shape=(40,), dtype=float64, numpy=
array([0.10215065, 0.31244912, 0.72099753, 0.09356474, 0.52338036,
       0.35602884, 0.52083   , 0.2700324 , 0.97333635, 0.98714759,
       0.35889202, 0.60202795, 0.30295656, 0.36815467, 0.94835201,
       0.29486974, 0.10381625, 0.51506259, 0.99287833, 0.20146318,
       0.6340266 , 0.05268368, 0.30967568, 0.28639171, 0.76262812,
       0.71452145, 0.17964069, 0.29756719, 0.34555487, 0.4893051 ,
       0.69491618, 0.91245949, 0.67148858, 0.43049428, 0.35770949,
       0.05298319, 0.66027812, 0.63326656, 0.44713664, 0.23436489])>

In [95]:
tf.reshape(F,shape=(2,2,10))

<tf.Tensor: shape=(2, 2, 10), dtype=float64, numpy=
array([[[0.10215065, 0.31244912, 0.72099753, 0.09356474, 0.52338036,
         0.35602884, 0.52083   , 0.2700324 , 0.97333635, 0.98714759],
        [0.35889202, 0.60202795, 0.30295656, 0.36815467, 0.94835201,
         0.29486974, 0.10381625, 0.51506259, 0.99287833, 0.20146318]],

       [[0.6340266 , 0.05268368, 0.30967568, 0.28639171, 0.76262812,
         0.71452145, 0.17964069, 0.29756719, 0.34555487, 0.4893051 ],
        [0.69491618, 0.91245949, 0.67148858, 0.43049428, 0.35770949,
         0.05298319, 0.66027812, 0.63326656, 0.44713664, 0.23436489]]])>

In [96]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=18>

In [97]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [98]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9928783252107543>

In [99]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.05268367711279498>

Squeezing a tensor (removing all single dimensions) 
`tf.squeeze()`

In [100]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G.shape, G.ndim


(TensorShape([1, 1, 1, 1, 50]), 5)

In [101]:
G_squeezed=tf.squeeze(G)

In [102]:
G_squeezed

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([87, 59, 57, 31, 97, 65, 36, 12, 72, 19, 79, 72, 70,  8, 77, 52, 14,
       63, 15, 13, 57, 91, 53, 87, 55, 24,  7, 97, 90,  2, 25, 34, 96, 87,
       89, 89, 77, 19, 37, 64, 45,  6, 86, 71, 18, 14, 17, 25, 60, 57])>